#include "main.h"
#include <stdio.h>
#include <stdlib.h>
#include "images/fires.h"
#include "images/heaven.h"
#include "images/souls.h"
#include "images/hell.h"
#include "images/end.h"
#include "gba.h"

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not required to use
// these specific provided states.
enum gba_state {
  PRE,
  START,
  MED,
  PLAY,
  WINA,
  IMPA,
  IMP,
  WIN,
  LOSE,
  LOST,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = PRE;

  fillScreenDMA(BLACK);

  char text[] = "GET READY"; // Text to animate
  int textX = 30;             // Initial X position of the text
  int textY = 20;             // Initial Y position of the text
  int dx = 2;                 // Change in X position per frame
  int dy = 1;                 // Change in Y position per frame
  int interval = 10;          // Interval for text animation (number of frames)
  char reserve[70];

  int frameCount = 0; // Counter for frames
  struct hell obj = {70, 0};
  struct hell obj1 = {HELL_WIDTH, HELL_HEIGHT + 60};
  struct hell obj2 = {HELL_WIDTH, HELL_HEIGHT + 40};
  struct hell obj5 = {HELL_WIDTH, HELL_HEIGHT + 80};
  struct hell obj6 = {HELL_WIDTH, HELL_HEIGHT + 100};
  struct hell obj7 = {10, 10};
  struct hell obj3 = {0, 0};
  struct hell obj4 = {0, 0};
  int counter = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    // Manipulate the state machine below as needed
    waitForVBlank();

    switch (state) {
      case PRE:
        drawFullScreenImageDMA(firepng);
        state = START;
        break;
      case START:
        drawString(50, 30, "THE WALK OF FIRE - Vishruth Anand", WHITE);
        drawString(80, 30, "PRESS START", WHITE);
        // Animate text
        if (frameCount % interval == 0) {
          // Move text
          textX += dx;

          // Reverse direction if text reaches screen boundaries
          if (textX <= 0 || textX >= WIDTH - 8) {
            dx = -dx;
          }
        }

        // Clear previous text
        drawRectDMA(textY - dy, textX - dx, 8 * 7, 8, BLACK);

        // Draw text at new position
        drawString(textY, textX, text, RED);

        frameCount++; // Increment frame count
        if (KEY_DOWN(BUTTON_START, currentButtons)) {
          state = MED;
        }
        break;

      case MED:
        fillScreenDMA(RED);
        state = PLAY;
        break;
      case PLAY:
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (obj.col < WIDTH - SOULS_WIDTH) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.col++;
          }
        }

        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (obj.col > 0) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.col--;
          }
        }

        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (obj.row > 0) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.row--;
          }
        }

        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (obj.row < HEIGHT - SOULS_HEIGHT) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.row++;
          }
        }
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = PRE;
          obj.row = 70;
          obj.col = 0;
          obj1.row = HELL_WIDTH;
          obj1.col = HELL_HEIGHT + 60;
          obj2.row = HELL_WIDTH;
          obj2.col = HELL_HEIGHT + 40;
          obj3.row = 0;
          obj3.col = 0;
          obj4.row = 0;
          obj4.col = 0;
          obj5.row = HELL_WIDTH;
          obj5.col = HELL_HEIGHT + 80;
          obj6.row = HELL_WIDTH;
          obj6.col = HELL_HEIGHT + 100;
          obj7.row = 10;
          obj7.col = 10;
          counter = 0;
        }
        drawImageDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, souls);
        drawRectDMA(obj1.row, obj1.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj1.row++;
        drawImageDMA(obj1.row, obj1.col, HELL_WIDTH, HELL_HEIGHT, hell);

        drawRectDMA(obj2.row, obj2.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj2.row = obj2.row + 2;
        drawImageDMA(obj2.row, obj2.col, HELL_WIDTH, HELL_HEIGHT, hell);
        drawRectDMA(obj3.row, obj3.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj3.row--; // Move the object upwards
        drawImageDMA(obj3.row, obj3.col, HELL_WIDTH, HELL_HEIGHT, hell);

        drawRectDMA(obj4.row, obj4.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj4.row = obj4.row + 2; // Move the object upwards
        drawImageDMA(obj4.row, obj4.col, HELL_WIDTH, HELL_HEIGHT, hell);

        waitForVBlank();

        if (obj1.row == 160) {
          obj1.row = 0;
          obj1.col = rand() % 220;
          counter++;
          snprintf(reserve, 70, "K:%d", counter);
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj3.row + HELL_HEIGHT == 0) {
          obj3.row = HEIGHT;      // Reset the object's position to the bottom of the screen
          obj3.col = rand() % 220; // Generate a random column position
          counter++;               // Increment score
          snprintf(reserve, 70, "K:%d", counter); // Update score display
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj4.row + HELL_HEIGHT == 0) {
          obj4.row = HEIGHT;      // Reset the object's position to the bottom of the screen
          obj4.col = rand() % 220; // Generate a random column position
          counter++;               // Increment score
          snprintf(reserve, 70, "K:%d", counter); // Update score display
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj2.row == 160) {
          obj2.row = 0;
          obj2.col = rand() % 220;
          counter++;
          snprintf(reserve, 70, "K:%d", counter);
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();

        if (obj.row + (SOULS_HEIGHT / 2) >= obj1.row && obj.row + (SOULS_HEIGHT / 2) <= obj1.row + HELL_HEIGHT && obj.col + (SOULS_WIDTH / 2) >= obj1.col && obj.col + (SOULS_WIDTH / 2) <= obj1.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.row + (SOULS_HEIGHT / 2) >= obj2.row && obj.row + (SOULS_HEIGHT / 2) <= obj2.row + HELL_HEIGHT && obj.col + (SOULS_WIDTH / 2) >= obj2.col && obj.col + (SOULS_WIDTH / 2) <= obj2.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.row + (SOULS_HEIGHT / 2) >= obj3.row &&
            obj.row + (SOULS_HEIGHT / 2) <= obj3.row + HELL_HEIGHT &&
            obj.col + (SOULS_WIDTH / 2) >= obj3.col &&
            obj.col + (SOULS_WIDTH / 2) <= obj3.col + HELL_WIDTH) {
          state = LOSE;
        }

        // Collision detection for obj4
        if (obj.row + (SOULS_HEIGHT / 2) >= obj4.row &&
            obj.row + (SOULS_HEIGHT / 2) <= obj4.row + HELL_HEIGHT &&
            obj.col + (SOULS_WIDTH / 2) >= obj4.col &&
            obj.col + (SOULS_WIDTH / 2) <= obj4.col + HELL_WIDTH) {
          state = LOSE;
        }

        if (obj.col == 220) {
          state = WIN;
        }
        // state = ?
        break;
      case WIN:
        drawFullScreenImageDMA(heaven);
        drawString(50, 55, "You have attained salvation!", BLACK);
        drawString(75, 45, "Press left for IMPOSSIBLE MODE", BLACK);
        drawString(100, 55, "Press backspace to restart", BLACK);
        state = WINA;
        break;
      case WINA:
        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          state = IMPA;
          obj.row = 70;
          obj.col = 0;
          obj1.row = HELL_WIDTH;
          obj1.col = HELL_HEIGHT + 60;
          obj2.row = HELL_WIDTH;
          obj2.col = HELL_HEIGHT + 40;
          obj3.row = 0;
          obj3.col = 0;
          obj4.row = 0;
          obj4.col = 0;
          counter = 0;
        }
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = PRE;
          obj.row = 70;
          obj.col = 0;
          obj1.row = HELL_WIDTH;
          obj1.col = HELL_HEIGHT + 60;
          obj2.row = HELL_WIDTH;
          obj2.col = HELL_HEIGHT + 40;
          obj3.row = 0;
          obj3.col = 0;
          obj4.row = 0;
          obj4.col = 0;
          obj5.row = HELL_WIDTH;
          obj5.col = HELL_HEIGHT + 80;
          obj6.row = HELL_WIDTH;
          obj6.col = HELL_HEIGHT + 100;
          obj7.row = 10;
          obj7.col = 10;
          counter = 0;
        }
        // state = ?
        break;
      case IMPA:
        fillScreenDMA(RED);
        state = IMP;
        break;
      case IMP:
        if (KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if (obj.col < WIDTH - SOULS_WIDTH) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.col++;
          }
        }

        if (KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if (obj.col > 0) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.col--;
          }
        }

        if (KEY_DOWN(BUTTON_UP, currentButtons)) {
          if (obj.row > 0) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.row--;
          }
        }

        if (KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if (obj.row < HEIGHT - SOULS_HEIGHT) {
            drawRectDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, RED);
            obj.row++;
          }
        }
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = PRE;
          obj.row = 70;
          obj.col = 0;
          obj1.row = HELL_WIDTH;
          obj1.col = HELL_HEIGHT + 60;
          obj2.row = HELL_WIDTH;
          obj2.col = HELL_HEIGHT + 40;
          obj3.row = 0;
          obj3.col = 0;
          obj4.row = 0;
          obj4.col = 0;
          obj5.row = HELL_WIDTH;
          obj5.col = HELL_HEIGHT + 80;
          obj6.row = HELL_WIDTH;
          obj6.col = HELL_HEIGHT + 100;
          obj7.row = 10;
          obj7.col = 10;
          counter = 0;
        }
        drawImageDMA(obj.row, obj.col, SOULS_WIDTH, SOULS_HEIGHT, souls);
        drawRectDMA(obj1.row, obj1.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj1.row += 2;
        drawImageDMA(obj1.row, obj1.col, HELL_WIDTH, HELL_HEIGHT, hell);

        drawRectDMA(obj2.row, obj2.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj2.row = obj2.row + 3;
        drawImageDMA(obj2.row, obj2.col, HELL_WIDTH, HELL_HEIGHT, hell);
        drawRectDMA(obj3.row, obj3.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj3.row -= 2; // Move the object upwards
        drawImageDMA(obj3.row, obj3.col, HELL_WIDTH, HELL_HEIGHT, hell);

        drawRectDMA(obj4.row, obj4.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj4.row -= 3; // Move the object upwards
        drawImageDMA(obj4.row, obj4.col, HELL_WIDTH, HELL_HEIGHT, hell);
        drawRectDMA(obj5.row, obj5.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj5.row += 4;
        drawImageDMA(obj5.row, obj5.col, HELL_WIDTH, HELL_HEIGHT, hell);
        waitForVBlank();
        drawRectDMA(obj6.row, obj6.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj6.row += 3;
        drawImageDMA(obj6.row, obj6.col, HELL_WIDTH, HELL_HEIGHT, hell);
        drawRectDMA(obj7.row, obj7.col, HELL_WIDTH, HELL_HEIGHT, RED);
        obj7.row -= 2; // Move the object upwards
        drawImageDMA(obj7.row, obj7.col, HELL_WIDTH, HELL_HEIGHT, hell);
        waitForVBlank();

        if (obj1.row == 160) {
          obj1.row = 0;
          obj1.col = rand() % 220;
          counter++;
          snprintf(reserve, 70, "K:%d", counter);
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj3.row + HELL_HEIGHT == 0) {
          obj3.row = HEIGHT; // Reset the object's position to the bottom of the screen
          obj3.col = rand() % 220; // Generate a random column position
          counter++;               // Increment score
          snprintf(reserve, 70, "K:%d", counter); // Update score display
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj4.row + HELL_HEIGHT == 0) {
          obj4.row = HEIGHT;      // Reset the object's position to the bottom of the screen
          obj4.col = rand() % 220; // Generate a random column position
          counter++;               // Increment score
          snprintf(reserve, 70, "K:%d", counter); // Update score display
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj2.row == 160) {
          obj2.row = 0;
          obj2.col = rand() % 220;
          counter++;
          snprintf(reserve, 70, "K:%d", counter);
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj5.row == 160) {
          obj5.row = 0;
          obj5.col = rand() % 220;
          counter++;
          snprintf(reserve, 70, "K:%d", counter);
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj6.row == 160) {
          obj6.row = 0;
          obj6.col = rand() % 220;
          counter++;
          snprintf(reserve, 70, "K:%d", counter);
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();
        if (obj7.row + HELL_HEIGHT == 0) {
          obj7.row = HEIGHT;      // Reset the object's position to the bottom of the screen
          obj7.col = rand() % 220; // Generate a random column position
          counter++;               // Increment score
          snprintf(reserve, 70, "K:%d", counter); // Update score display
          drawRectDMA(5, 200, 50, 10, RED);
          drawString(5, 200, reserve, BLACK);
        }
        waitForVBlank();

        if (obj.row + (SOULS_HEIGHT / 2) >= obj1.row && obj.row + (SOULS_HEIGHT / 2) <= obj1.row + HELL_HEIGHT && obj.col + (SOULS_WIDTH / 2) >= obj1.col && obj.col + (SOULS_WIDTH / 2) <= obj1.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.row + (SOULS_HEIGHT / 2) >= obj2.row && obj.row + (SOULS_HEIGHT / 2) <= obj2.row + HELL_HEIGHT && obj.col + (SOULS_WIDTH / 2) >= obj2.col && obj.col + (SOULS_WIDTH / 2) <= obj2.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.row + (SOULS_HEIGHT / 2) >= obj3.row &&
            obj.row + (SOULS_HEIGHT / 2) <= obj3.row + HELL_HEIGHT &&
            obj.col + (SOULS_WIDTH / 2) >= obj3.col &&
            obj.col + (SOULS_WIDTH / 2) <= obj3.col + HELL_WIDTH) {
          state = LOSE;
        }

        // Collision detection for obj4
        if (obj.row + (SOULS_HEIGHT / 2) >= obj4.row &&
            obj.row + (SOULS_HEIGHT / 2) <= obj4.row + HELL_HEIGHT &&
            obj.col + (SOULS_WIDTH / 2) >= obj4.col &&
            obj.col + (SOULS_WIDTH / 2) <= obj4.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.row + (SOULS_HEIGHT / 2) >= obj7.row &&
            obj.row + (SOULS_HEIGHT / 2) <= obj7.row + HELL_HEIGHT &&
            obj.col + (SOULS_WIDTH / 2) >= obj7.col &&
            obj.col + (SOULS_WIDTH / 2) <= obj7.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.row + (SOULS_HEIGHT / 2) >= obj6.row &&
            obj.row + (SOULS_HEIGHT / 2) <= obj6.row + HELL_HEIGHT &&
            obj.col + (SOULS_WIDTH / 2) >= obj6.col &&
            obj.col + (SOULS_WIDTH / 2) <= obj6.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.row + (SOULS_HEIGHT / 2) >= obj5.row &&
            obj.row + (SOULS_HEIGHT / 2) <= obj5.row + HELL_HEIGHT &&
            obj.col + (SOULS_WIDTH / 2) >= obj5.col &&
            obj.col + (SOULS_WIDTH / 2) <= obj5.col + HELL_WIDTH) {
          state = LOSE;
        }
        if (obj.col == 220) {
          state = WIN;
        }
        // state = ?
        break;
      case LOSE:
        drawFullScreenImageDMA(end);
        drawString(50, 95, "You lost", RED);
        drawString(100, 55, "Press backspace to restart", RED);
        state = LOST;
        break;
      case LOST:
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          state = PRE;
          obj.row = 70;
          obj.col = 0;
          obj1.row = HELL_WIDTH;
          obj1.col = HELL_HEIGHT + 60;
          obj2.row = HELL_WIDTH;
          obj2.col = HELL_HEIGHT + 40;
          obj3.row = 0;
          obj3.col = 0;
          obj4.row = 0;
          obj4.col = 0;
          obj5.row = HELL_WIDTH;
          obj5.col = HELL_HEIGHT + 80;
          obj6.row = HELL_WIDTH;
          obj6.col = HELL_HEIGHT + 100;
          obj7.row = 10;
          obj7.col = 10;
          counter = 0;
        }
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }
UNUSED(previousButtons);
  return 0;
}
